# Generated by Django 4.2.5 on 2023-09-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='cuser',
            name='addressBlock',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cuser',
            name='addressCommunity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuser',
            name='addressFlatNo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
