# Generated by Django 4.2.5 on 2023-09-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(blank=True, max_length=50, null=True)),
                ('categoryImage', models.ImageField(blank=True, null=True, upload_to='product_images/categoryImg')),
            ],
        ),
    ]
