# Generated by Django 4.2.5 on 2023-09-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categorieslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselbanner',
            name='bannerImage',
            field=models.ImageField(default='', upload_to='media/product_images/bannerImg'),
        ),
        migrations.AlterField(
            model_name='categorieslist',
            name='categoryImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images/categoryImg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images/itemImg'),
        ),
    ]
