# Generated by Django 4.2.5 on 2023-09-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subcategorieslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images/profile'),
        ),
    ]
